/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N1N2MessageCollectionDocumentApiImpl.h"
#include "itti.hpp"

#include "amf_app.hpp"
#include "amf_sbi.hpp"
#include "pdu_session_context.hpp"
#include "conversions.hpp"
#include "output_wrapper.hpp"

using namespace amf_application;

extern itti_mw* itti_inst;
extern amf_app* amf_app_inst;

namespace oai {
namespace amf {
namespace api {

using namespace oai::amf::model;

N1N2MessageCollectionDocumentApiImpl::N1N2MessageCollectionDocumentApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr,
    amf_application::amf_app* amf_app_inst)
    : N1N2MessageCollectionDocumentApi(rtr), m_amf_app(amf_app_inst) {}

void N1N2MessageCollectionDocumentApiImpl::n1_n2_message_transfer(
      const std::string& ueContextId,
      std::unordered_map<std::string, mime_part>& parts,
      Pistache::Http::ResponseWriter& response){
  Logger::amf_server().debug(
      "Receive N1N2MessageTransfer Request, handling...");

  nlohmann::json response_json = {};
  response_json["cause"] =
      n1_n2_message_transfer_cause_e2str[N1_N2_TRANSFER_INITIATED];
  Pistache::Http::Code code = Pistache::Http::Code::Ok;

  std::string supi = ueContextId;
  
  N1N2MessageTransferReqData n1N2MessageTransferReqData = {};
  nlohmann::json::parse(parts["root"].body.c_str()).get_to(n1N2MessageTransferReqData);

  if(n1N2MessageTransferReqData.n2InfoContainerIsSet()){
    // N2 Container Present
    Logger::amf_server().debug(
        "Receive N1N2MessageTransfer Request, handling...");

    nlohmann::json response_json = {};
    response_json["cause"] =
        n1_n2_message_transfer_cause_e2str[N1_N2_TRANSFER_INITIATED];
    Pistache::Http::Code code = Pistache::Http::Code::Ok;

    std::string supi = ueContextId;
    if(n1N2MessageTransferReqData.getN2InfoContainer().getN2InformationClass().getEnumValue() == N2InformationClass_anyOf::eN2InformationClass_anyOf::SM) {
      // N2 SM Container Present
      Logger::amf_server().debug("N2 Information Class is N2_INFORMATION_CLASS_SM");
      Logger::amf_server().debug(
        "Key for PDU Session context: SUPI (%s)", supi.c_str());
      std::shared_ptr<pdu_session_context> psc = {};
      bool request_valid                       = true;

      if (!amf_app_inst->find_pdu_session_context(
              supi, (uint8_t) n1N2MessageTransferReqData.getPduSessionId(), psc)) {
        Logger::amf_server().error(
            "Cannot get pdu_session_context with SUPI (%s)", supi.c_str());
        request_valid = false;
      }

      if(!n1N2MessageTransferReqData.n1MessageContainerIsSet() || n1N2MessageTransferReqData.getN1MessageContainer().getN1MessageClass().getEnumValue() != N1MessageClass_anyOf::eN1MessageClass_anyOf::SM){
        Logger::amf_server().error("N1 Message Container is not present or N1 Message Class is not N1_MESSAGE_CLASS_SM");
        request_valid = false;
      }

      std::string n1_content_id = n1N2MessageTransferReqData.getN1MessageContainer().getN1MessageContent().getContentId();
      std::string n2_content_id = n1N2MessageTransferReqData.getN2InfoContainer().getSmInfo().getN2InfoContent().getNgapData().getContentId();

      Logger::amf_server().debug("n1_content_id: %s", n1_content_id.c_str());
      Logger::amf_server().debug("n2_content_id: %s", n2_content_id.c_str());
      if (parts.count(n1_content_id) == 0 || parts[n1_content_id].body.size() == 0 || parts.count(n2_content_id) == 0 || parts[n2_content_id].body.size() == 0) {
        Logger::amf_server().error(
            "Missing n1sm or n2sm Mime Part");
        request_valid = false;
      }

      if (!request_valid) {
        code = Pistache::Http::Code::Bad_Request;
        response_json["cause"] =
            n1_n2_message_transfer_cause_e2str[N1_MSG_NOT_TRANSFERRED];
        // Send response to the NF Service Consumer (e.g., SMF)
        response.send(code, response_json.dump().c_str());
        return;
      }

      bstring n1sm = nullptr;
      conv::msg_str_2_msg_hex(parts[n1_content_id].body.substr(0, parts[n1_content_id].body.length()), n1sm);

      bstring n2sm = nullptr;
      conv::msg_str_2_msg_hex(parts[n2_content_id].body, n2sm);

      psc->n1sm              = bstrcpy(n1sm);
      psc->is_n1sm_avaliable = true;
      psc->n2sm              = bstrcpy(n2sm);
      psc->is_n2sm_avaliable = true;
      Logger::amf_server().debug("n2sm size in amf_server(%d)", blength(psc->n2sm));

      auto itti_msg = std::make_shared<itti_n1n2_message_transfer_request>(
          AMF_SERVER, TASK_AMF_APP);
      itti_msg->supi        = ueContextId;
      itti_msg->n1sm        = bstrcpy(n1sm);
      itti_msg->is_n1sm_set = true;
      itti_msg->n2sm        = bstrcpy(n2sm);
      itti_msg->is_n2sm_set = true;
      itti_msg->pdu_session_id =
          (uint8_t) n1N2MessageTransferReqData.getPduSessionId();
      nlohmann::json ngap_ie_type = {};
      to_json(
          ngap_ie_type, n1N2MessageTransferReqData.getN2InfoContainer()
                            .getSmInfo()
                            .getN2InfoContent()
                            .getNgapIeType()
                            .getValue());
      std::string ngap_type = ngap_ie_type.dump();
      ngap_type = ngap_type.substr(1, ngap_type.length()-2);
      Logger::amf_server().debug(
          "This is testing.... NGAP IE Type: %s", ngap_type.c_str());
      itti_msg->n2sm_info_type = ngap_type;

      // For Paging
      if (n1N2MessageTransferReqData.ppiIsSet()) {
        itti_msg->is_ppi_set = true;
        itti_msg->ppi        = n1N2MessageTransferReqData.getPpi();
        response_json["cause"] =
            n1_n2_message_transfer_cause_e2str[ATTEMPTING_TO_REACH_UE];
        code = Pistache::Http::Code::Accepted;
      } else {
        itti_msg->is_ppi_set = false;
      }

      // Send response to the NF Service Consumer (e.g., SMF)
      response.send(code, response_json.dump().c_str());

      // Process N1N2 Message Transfer Request
      int ret = itti_inst->send_msg(itti_msg);
      if (0 != ret) {
        Logger::amf_server().error(
            "Could not send ITTI message %s to task TASK_AMF_N2",
            itti_msg->get_msg_name());
      }
      bdestroy_wrapper(&n1sm);
      bdestroy_wrapper(&n2sm);
    }
    else if(n1N2MessageTransferReqData.getN2InfoContainer().getN2InformationClass().getEnumValue() == N2InformationClass_anyOf::eN2InformationClass_anyOf::NRPPA) {
      // N2 NRPPA Container Present
      bool request_valid                       = true;
      std::string n2_content_id = n1N2MessageTransferReqData.getN2InfoContainer().getNrppaInfo().getNrppaPdu().getNgapData().getContentId();
      Logger::amf_server().debug("n2_content_id: %s", n2_content_id.c_str());
      if (parts.count(n2_content_id) == 0 || parts[n2_content_id].body.size() == 0) {
        Logger::amf_server().error(
            "Missing N2 Mime Part");
        request_valid = false;
      }

      if (!request_valid) {
        code = Pistache::Http::Code::Bad_Request;
        response_json["cause"] =
            n1_n2_message_transfer_cause_e2str[N1_MSG_NOT_TRANSFERRED];
        // Send response to the NF Service Consumer (e.g., SMF)
        response.send(code, response_json.dump().c_str());
        return;
      }

      bstring nrppa_pdu = nullptr;
      bstring routing_id = nullptr;
      conv::msg_str_2_msg_hex(parts[n2_content_id].body, nrppa_pdu);
      conv::string_2_bstring(n1N2MessageTransferReqData.getN2InfoContainer()
                            .getNrppaInfo().getNfId(), routing_id);
      auto itti_msg = std::make_shared<itti_n1n2_message_transfer_request>(
          AMF_SERVER, TASK_AMF_APP);
      itti_msg->supi        = ueContextId;
      itti_msg->is_n1sm_set = false;
      itti_msg->is_n2sm_set = false;
      itti_msg->nrppa_pdu   = bstrcpy(nrppa_pdu);
      itti_msg->routing_id  = bstrcpy(routing_id);

      itti_msg->is_nrppa_pdu_set = true;
      nlohmann::json ngap_ie_type = {};
      to_json(
          ngap_ie_type, n1N2MessageTransferReqData.getN2InfoContainer()
                            .getNrppaInfo()
                            .getNrppaPdu()
                            .getNgapIeType()
                            .getValue());
      std::string ngap_type = ngap_ie_type.dump();
      ngap_type = ngap_type.substr(1, ngap_type.length()-2);
      Logger::amf_server().debug(
          "This is testing.... NGAP IE Type: %s", ngap_type.c_str());
      itti_msg->n2sm_info_type = ngap_type;
      response.send(code, response_json.dump().c_str());

      // Process N1N2 Message Transfer Request
      int ret = itti_inst->send_msg(itti_msg);
      if (0 != ret) {
        Logger::amf_server().error(
            "Could not send ITTI message %s to task TASK_AMF_N2",
            itti_msg->get_msg_name());
      }
      bdestroy_wrapper(&nrppa_pdu);
    }
    else {
      response.send(
        Pistache::Http::Code::Ok,
        "N1N2MessageCollectionDocumentApiImpl::n1_n2_message_transfer API (Unsupported N2 Message Class)");
    }
  }
  else if(n1N2MessageTransferReqData.n1MessageContainerIsSet()){
    // N1 Container Present
    if(n1N2MessageTransferReqData.getN1MessageContainer().getN1MessageClass().getEnumValue() == N1MessageClass_anyOf::eN1MessageClass_anyOf::SM){
      // N1 SM Container Present
      Logger::amf_server().debug(
        "Key for PDU Session context: SUPI (%s)", supi.c_str());
      std::shared_ptr<pdu_session_context> psc = {};
      bool request_valid                       = true;
      if (!amf_app_inst->find_pdu_session_context(
              supi, (uint8_t) n1N2MessageTransferReqData.getPduSessionId(), psc)) {
        Logger::amf_server().error(
            "Cannot get pdu_session_context with SUPI (%s)", supi.c_str());
        request_valid = false;
      }

      std::string content_id = n1N2MessageTransferReqData.getN1MessageContainer().getN1MessageContent().getContentId();
      Logger::amf_server().debug("n1_content_id: %s", content_id.c_str());

      if (parts.count(content_id) == 0 || parts[content_id].body.size() == 0) {
        request_valid = false;
      }
      if (!request_valid) {
        code = Pistache::Http::Code::Bad_Request;
        response_json["cause"] =
            n1_n2_message_transfer_cause_e2str[N1_MSG_NOT_TRANSFERRED];
        // Send response to the NF Service Consumer (e.g., SMF)
        response.send(code, response_json.dump().c_str());
        return;
      }

      bstring n1sm = nullptr;
      conv::msg_str_2_msg_hex(parts[content_id].body.substr(0, parts[content_id].body.length()), n1sm);
      output_wrapper::print_buffer(
          "amf_server", "Received N1 SM", (uint8_t*) bdata(n1sm), blength(n1sm));

      psc->n1sm              = bstrcpy(n1sm);
      psc->is_n1sm_avaliable = true;
      psc->is_n2sm_avaliable = false;

      auto itti_msg = std::make_shared<itti_n1n2_message_transfer_request>(
      AMF_SERVER, TASK_AMF_APP);
      itti_msg->supi        = ueContextId;
      itti_msg->n1sm        = bstrcpy(n1sm);
      itti_msg->is_n1sm_set = true;
      itti_msg->n2sm        = nullptr;
      itti_msg->is_n2sm_set = false;
      itti_msg->pdu_session_id =
          (uint8_t) n1N2MessageTransferReqData.getPduSessionId();

      // For Paging
      if (n1N2MessageTransferReqData.ppiIsSet()) {
        itti_msg->is_ppi_set = true;
        itti_msg->ppi        = n1N2MessageTransferReqData.getPpi();
        response_json["cause"] =
            n1_n2_message_transfer_cause_e2str[ATTEMPTING_TO_REACH_UE];
        code = Pistache::Http::Code::Accepted;
      } else {
        itti_msg->is_ppi_set = false;
      }

      // Send response to the NF Service Consumer (e.g., SMF)
      response.send(code, response_json.dump().c_str());

      // Process N1N2 Message Transfer Request
      int ret = itti_inst->send_msg(itti_msg);
      if (0 != ret) {
        Logger::amf_server().error(
            "Could not send ITTI message %s to task TASK_AMF_N2",
            itti_msg->get_msg_name());
      }

      bdestroy_wrapper(&n1sm);
    }
    else if(n1N2MessageTransferReqData.getN1MessageContainer().getN1MessageClass().getEnumValue() == N1MessageClass_anyOf::eN1MessageClass_anyOf::LPP){
      // N1 LPP Container Present
      response.send(
        Pistache::Http::Code::Ok,
        "N1N2MessageCollectionDocumentApiImpl::n1_n2_message_transfer API (Unsupported N1 Message Class)");
    }
    else {
      response.send(
        Pistache::Http::Code::Ok,
        "N1N2MessageCollectionDocumentApiImpl::n1_n2_message_transfer API (Unsupported N1 Message Class)");
    }
  }

}

}  // namespace api
}  // namespace amf
}  // namespace oai
