/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice
 * -no-gen-example -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -D src`
 */

#include "Ngap_UEPagingIdentity.h"

#include "Ngap_FiveG-S-TMSI.h"
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_Ngap_UEPagingIdentity_constr_1
    CC_NOTUSED = {{0, 0}, -1};
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Ngap_UEPagingIdentity_constr_1 CC_NOTUSED = {
    {APC_CONSTRAINED | APC_EXTENSIBLE, 0, 0, 0, 0} /* (0..0,...) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_Ngap_UEPagingIdentity_1[] = {
    {ATF_POINTER,
     0,
     offsetof(struct Ngap_UEPagingIdentity, choice.fiveG_S_TMSI),
     (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_Ngap_FiveG_S_TMSI,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
         0},
     0,
     0, /* No default value */
     "fiveG-S-TMSI"},
};
static const asn_TYPE_tag2member_t asn_MAP_Ngap_UEPagingIdentity_tag2el_1[] = {
    {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0} /* fiveG-S-TMSI */
};
asn_CHOICE_specifics_t asn_SPC_Ngap_UEPagingIdentity_specs_1 = {
    sizeof(struct Ngap_UEPagingIdentity),
    offsetof(struct Ngap_UEPagingIdentity, _asn_ctx),
    offsetof(struct Ngap_UEPagingIdentity, present),
    sizeof(((struct Ngap_UEPagingIdentity*) 0)->present),
    asn_MAP_Ngap_UEPagingIdentity_tag2el_1,
    1, /* Count of tags in the map */
    0,
    0,
    1 /* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Ngap_UEPagingIdentity = {
    "UEPagingIdentity",
    "UEPagingIdentity",
    &asn_OP_CHOICE,
    0, /* No effective tags (pointer) */
    0, /* No effective tags (count) */
    0, /* No tags (pointer) */
    0, /* No tags (count) */
    {
#if !defined(ASN_DISABLE_OER_SUPPORT)
        &asn_OER_type_Ngap_UEPagingIdentity_constr_1,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
        &asn_PER_type_Ngap_UEPagingIdentity_constr_1,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
        CHOICE_constraint},
    asn_MBR_Ngap_UEPagingIdentity_1,
    1,                                     /* Elements count */
    &asn_SPC_Ngap_UEPagingIdentity_specs_1 /* Additional specs */
};
