/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice
 * -no-gen-example -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -D src`
 */

#include "Ngap_AreaScopeOfMDT-EUTRA.h"

#include "Ngap_CellBasedMDT-EUTRA.h"
#include "Ngap_TABasedMDT.h"
#include "Ngap_TAIBasedMDT.h"
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_Ngap_AreaScopeOfMDT_EUTRA_constr_1
    CC_NOTUSED = {{0, 0}, -1};
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Ngap_AreaScopeOfMDT_EUTRA_constr_1
    CC_NOTUSED = {
        {APC_CONSTRAINED | APC_EXTENSIBLE, 2, 2, 0, 3} /* (0..3,...) */,
        {APC_UNCONSTRAINED, -1, -1, 0, 0},
        0,
        0 /* No PER value map */
};
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_Ngap_AreaScopeOfMDT_EUTRA_1[] = {
    {ATF_POINTER,
     0,
     offsetof(struct Ngap_AreaScopeOfMDT_EUTRA, choice.cellBased),
     (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_Ngap_CellBasedMDT_EUTRA,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
         0},
     0,
     0, /* No default value */
     "cellBased"},
    {ATF_POINTER,
     0,
     offsetof(struct Ngap_AreaScopeOfMDT_EUTRA, choice.tABased),
     (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_Ngap_TABasedMDT,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
         0},
     0,
     0, /* No default value */
     "tABased"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct Ngap_AreaScopeOfMDT_EUTRA, choice.pLMNWide),
     (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NULL,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
         0},
     0,
     0, /* No default value */
     "pLMNWide"},
    {ATF_POINTER,
     0,
     offsetof(struct Ngap_AreaScopeOfMDT_EUTRA, choice.tAIBased),
     (ASN_TAG_CLASS_CONTEXT | (3 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_Ngap_TAIBasedMDT,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
         0},
     0,
     0, /* No default value */
     "tAIBased"},
};
static const asn_TYPE_tag2member_t
    asn_MAP_Ngap_AreaScopeOfMDT_EUTRA_tag2el_1[] = {
        {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0}, /* cellBased */
        {(ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0}, /* tABased */
        {(ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0}, /* pLMNWide */
        {(ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0}  /* tAIBased */
};
asn_CHOICE_specifics_t asn_SPC_Ngap_AreaScopeOfMDT_EUTRA_specs_1 = {
    sizeof(struct Ngap_AreaScopeOfMDT_EUTRA),
    offsetof(struct Ngap_AreaScopeOfMDT_EUTRA, _asn_ctx),
    offsetof(struct Ngap_AreaScopeOfMDT_EUTRA, present),
    sizeof(((struct Ngap_AreaScopeOfMDT_EUTRA*) 0)->present),
    asn_MAP_Ngap_AreaScopeOfMDT_EUTRA_tag2el_1,
    4, /* Count of tags in the map */
    0,
    0,
    4 /* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Ngap_AreaScopeOfMDT_EUTRA = {
    "AreaScopeOfMDT-EUTRA",
    "AreaScopeOfMDT-EUTRA",
    &asn_OP_CHOICE,
    0, /* No effective tags (pointer) */
    0, /* No effective tags (count) */
    0, /* No tags (pointer) */
    0, /* No tags (count) */
    {
#if !defined(ASN_DISABLE_OER_SUPPORT)
        &asn_OER_type_Ngap_AreaScopeOfMDT_EUTRA_constr_1,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
        &asn_PER_type_Ngap_AreaScopeOfMDT_EUTRA_constr_1,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
        CHOICE_constraint},
    asn_MBR_Ngap_AreaScopeOfMDT_EUTRA_1,
    4,                                         /* Elements count */
    &asn_SPC_Ngap_AreaScopeOfMDT_EUTRA_specs_1 /* Additional specs */
};
