/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice
 * -no-gen-example -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -D src`
 */

#ifndef _Ngap_ProtocolIE_Container_H_
#define _Ngap_ProtocolIE_Container_H_

#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_PDUSessionResourceSetupRequestIEs;
struct Ngap_PDUSessionResourceSetupResponseIEs;
struct Ngap_PDUSessionResourceReleaseCommandIEs;
struct Ngap_PDUSessionResourceReleaseResponseIEs;
struct Ngap_PDUSessionResourceModifyRequestIEs;
struct Ngap_PDUSessionResourceModifyResponseIEs;
struct Ngap_PDUSessionResourceNotifyIEs;
struct Ngap_PDUSessionResourceModifyIndicationIEs;
struct Ngap_PDUSessionResourceModifyConfirmIEs;
struct Ngap_InitialContextSetupRequestIEs;
struct Ngap_InitialContextSetupResponseIEs;
struct Ngap_InitialContextSetupFailureIEs;
struct Ngap_UEContextReleaseRequest_IEs;
struct Ngap_UEContextReleaseCommand_IEs;
struct Ngap_UEContextReleaseComplete_IEs;
struct Ngap_UEContextResumeRequestIEs;
struct Ngap_UEContextResumeResponseIEs;
struct Ngap_UEContextResumeFailureIEs;
struct Ngap_UEContextSuspendRequestIEs;
struct Ngap_UEContextSuspendResponseIEs;
struct Ngap_UEContextSuspendFailureIEs;
struct Ngap_UEContextModificationRequestIEs;
struct Ngap_UEContextModificationResponseIEs;
struct Ngap_UEContextModificationFailureIEs;
struct Ngap_RRCInactiveTransitionReportIEs;
struct Ngap_RetrieveUEInformationIEs;
struct Ngap_UEInformationTransferIEs;
struct Ngap_RANCPRelocationIndicationIEs;
struct Ngap_HandoverRequiredIEs;
struct Ngap_HandoverCommandIEs;
struct Ngap_HandoverPreparationFailureIEs;
struct Ngap_HandoverRequestIEs;
struct Ngap_HandoverRequestAcknowledgeIEs;
struct Ngap_HandoverFailureIEs;
struct Ngap_HandoverNotifyIEs;
struct Ngap_PathSwitchRequestIEs;
struct Ngap_PathSwitchRequestAcknowledgeIEs;
struct Ngap_PathSwitchRequestFailureIEs;
struct Ngap_HandoverCancelIEs;
struct Ngap_HandoverCancelAcknowledgeIEs;
struct Ngap_HandoverSuccessIEs;
struct Ngap_UplinkRANEarlyStatusTransferIEs;
struct Ngap_DownlinkRANEarlyStatusTransferIEs;
struct Ngap_UplinkRANStatusTransferIEs;
struct Ngap_DownlinkRANStatusTransferIEs;
struct Ngap_PagingIEs;
struct Ngap_InitialUEMessage_IEs;
struct Ngap_DownlinkNASTransport_IEs;
struct Ngap_UplinkNASTransport_IEs;
struct Ngap_NASNonDeliveryIndication_IEs;
struct Ngap_RerouteNASRequest_IEs;
struct Ngap_NGSetupRequestIEs;
struct Ngap_NGSetupResponseIEs;
struct Ngap_NGSetupFailureIEs;
struct Ngap_RANConfigurationUpdateIEs;
struct Ngap_RANConfigurationUpdateAcknowledgeIEs;
struct Ngap_RANConfigurationUpdateFailureIEs;
struct Ngap_AMFConfigurationUpdateIEs;
struct Ngap_AMFConfigurationUpdateAcknowledgeIEs;
struct Ngap_AMFConfigurationUpdateFailureIEs;
struct Ngap_AMFStatusIndicationIEs;
struct Ngap_NGResetIEs;
struct Ngap_NGResetAcknowledgeIEs;
struct Ngap_ErrorIndicationIEs;
struct Ngap_OverloadStartIEs;
struct Ngap_OverloadStopIEs;
struct Ngap_UplinkRANConfigurationTransferIEs;
struct Ngap_DownlinkRANConfigurationTransferIEs;
struct Ngap_WriteReplaceWarningRequestIEs;
struct Ngap_WriteReplaceWarningResponseIEs;
struct Ngap_PWSCancelRequestIEs;
struct Ngap_PWSCancelResponseIEs;
struct Ngap_PWSRestartIndicationIEs;
struct Ngap_PWSFailureIndicationIEs;
struct Ngap_DownlinkUEAssociatedNRPPaTransportIEs;
struct Ngap_UplinkUEAssociatedNRPPaTransportIEs;
struct Ngap_DownlinkNonUEAssociatedNRPPaTransportIEs;
struct Ngap_UplinkNonUEAssociatedNRPPaTransportIEs;
struct Ngap_TraceStartIEs;
struct Ngap_TraceFailureIndicationIEs;
struct Ngap_DeactivateTraceIEs;
struct Ngap_CellTrafficTraceIEs;
struct Ngap_LocationReportingControlIEs;
struct Ngap_LocationReportingFailureIndicationIEs;
struct Ngap_LocationReportIEs;
struct Ngap_UETNLABindingReleaseRequestIEs;
struct Ngap_UERadioCapabilityInfoIndicationIEs;
struct Ngap_UERadioCapabilityCheckRequestIEs;
struct Ngap_UERadioCapabilityCheckResponseIEs;
struct Ngap_SecondaryRATDataUsageReportIEs;
struct Ngap_UplinkRIMInformationTransferIEs;
struct Ngap_DownlinkRIMInformationTransferIEs;
struct Ngap_ConnectionEstablishmentIndicationIEs;
struct Ngap_UERadioCapabilityIDMappingRequestIEs;
struct Ngap_UERadioCapabilityIDMappingResponseIEs;
struct Ngap_AMFCPRelocationIndicationIEs;
struct Ngap_PDUSessionResourceModifyRequestTransferIEs;
struct Ngap_PDUSessionResourceSetupRequestTransferIEs;

/* Ngap_ProtocolIE-Container */
typedef struct Ngap_ProtocolIE_Container_9666P0 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P0_t;
typedef struct Ngap_ProtocolIE_Container_9666P1 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P1_t;
typedef struct Ngap_ProtocolIE_Container_9666P2 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceReleaseCommandIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P2_t;
typedef struct Ngap_ProtocolIE_Container_9666P3 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceReleaseResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P3_t;
typedef struct Ngap_ProtocolIE_Container_9666P4 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P4_t;
typedef struct Ngap_ProtocolIE_Container_9666P5 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P5_t;
typedef struct Ngap_ProtocolIE_Container_9666P6 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceNotifyIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P6_t;
typedef struct Ngap_ProtocolIE_Container_9666P7 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P7_t;
typedef struct Ngap_ProtocolIE_Container_9666P8 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyConfirmIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P8_t;
typedef struct Ngap_ProtocolIE_Container_9666P9 {
  A_SEQUENCE_OF(struct Ngap_InitialContextSetupRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P9_t;
typedef struct Ngap_ProtocolIE_Container_9666P10 {
  A_SEQUENCE_OF(struct Ngap_InitialContextSetupResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P10_t;
typedef struct Ngap_ProtocolIE_Container_9666P11 {
  A_SEQUENCE_OF(struct Ngap_InitialContextSetupFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P11_t;
typedef struct Ngap_ProtocolIE_Container_9666P12 {
  A_SEQUENCE_OF(struct Ngap_UEContextReleaseRequest_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P12_t;
typedef struct Ngap_ProtocolIE_Container_9666P13 {
  A_SEQUENCE_OF(struct Ngap_UEContextReleaseCommand_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P13_t;
typedef struct Ngap_ProtocolIE_Container_9666P14 {
  A_SEQUENCE_OF(struct Ngap_UEContextReleaseComplete_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P14_t;
typedef struct Ngap_ProtocolIE_Container_9666P15 {
  A_SEQUENCE_OF(struct Ngap_UEContextResumeRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P15_t;
typedef struct Ngap_ProtocolIE_Container_9666P16 {
  A_SEQUENCE_OF(struct Ngap_UEContextResumeResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P16_t;
typedef struct Ngap_ProtocolIE_Container_9666P17 {
  A_SEQUENCE_OF(struct Ngap_UEContextResumeFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P17_t;
typedef struct Ngap_ProtocolIE_Container_9666P18 {
  A_SEQUENCE_OF(struct Ngap_UEContextSuspendRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P18_t;
typedef struct Ngap_ProtocolIE_Container_9666P19 {
  A_SEQUENCE_OF(struct Ngap_UEContextSuspendResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P19_t;
typedef struct Ngap_ProtocolIE_Container_9666P20 {
  A_SEQUENCE_OF(struct Ngap_UEContextSuspendFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P20_t;
typedef struct Ngap_ProtocolIE_Container_9666P21 {
  A_SEQUENCE_OF(struct Ngap_UEContextModificationRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P21_t;
typedef struct Ngap_ProtocolIE_Container_9666P22 {
  A_SEQUENCE_OF(struct Ngap_UEContextModificationResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P22_t;
typedef struct Ngap_ProtocolIE_Container_9666P23 {
  A_SEQUENCE_OF(struct Ngap_UEContextModificationFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P23_t;
typedef struct Ngap_ProtocolIE_Container_9666P24 {
  A_SEQUENCE_OF(struct Ngap_RRCInactiveTransitionReportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P24_t;
typedef struct Ngap_ProtocolIE_Container_9666P25 {
  A_SEQUENCE_OF(struct Ngap_RetrieveUEInformationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P25_t;
typedef struct Ngap_ProtocolIE_Container_9666P26 {
  A_SEQUENCE_OF(struct Ngap_UEInformationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P26_t;
typedef struct Ngap_ProtocolIE_Container_9666P27 {
  A_SEQUENCE_OF(struct Ngap_RANCPRelocationIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P27_t;
typedef struct Ngap_ProtocolIE_Container_9666P28 {
  A_SEQUENCE_OF(struct Ngap_HandoverRequiredIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P28_t;
typedef struct Ngap_ProtocolIE_Container_9666P29 {
  A_SEQUENCE_OF(struct Ngap_HandoverCommandIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P29_t;
typedef struct Ngap_ProtocolIE_Container_9666P30 {
  A_SEQUENCE_OF(struct Ngap_HandoverPreparationFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P30_t;
typedef struct Ngap_ProtocolIE_Container_9666P31 {
  A_SEQUENCE_OF(struct Ngap_HandoverRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P31_t;
typedef struct Ngap_ProtocolIE_Container_9666P32 {
  A_SEQUENCE_OF(struct Ngap_HandoverRequestAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P32_t;
typedef struct Ngap_ProtocolIE_Container_9666P33 {
  A_SEQUENCE_OF(struct Ngap_HandoverFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P33_t;
typedef struct Ngap_ProtocolIE_Container_9666P34 {
  A_SEQUENCE_OF(struct Ngap_HandoverNotifyIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P34_t;
typedef struct Ngap_ProtocolIE_Container_9666P35 {
  A_SEQUENCE_OF(struct Ngap_PathSwitchRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P35_t;
typedef struct Ngap_ProtocolIE_Container_9666P36 {
  A_SEQUENCE_OF(struct Ngap_PathSwitchRequestAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P36_t;
typedef struct Ngap_ProtocolIE_Container_9666P37 {
  A_SEQUENCE_OF(struct Ngap_PathSwitchRequestFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P37_t;
typedef struct Ngap_ProtocolIE_Container_9666P38 {
  A_SEQUENCE_OF(struct Ngap_HandoverCancelIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P38_t;
typedef struct Ngap_ProtocolIE_Container_9666P39 {
  A_SEQUENCE_OF(struct Ngap_HandoverCancelAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P39_t;
typedef struct Ngap_ProtocolIE_Container_9666P40 {
  A_SEQUENCE_OF(struct Ngap_HandoverSuccessIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P40_t;
typedef struct Ngap_ProtocolIE_Container_9666P41 {
  A_SEQUENCE_OF(struct Ngap_UplinkRANEarlyStatusTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P41_t;
typedef struct Ngap_ProtocolIE_Container_9666P42 {
  A_SEQUENCE_OF(struct Ngap_DownlinkRANEarlyStatusTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P42_t;
typedef struct Ngap_ProtocolIE_Container_9666P43 {
  A_SEQUENCE_OF(struct Ngap_UplinkRANStatusTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P43_t;
typedef struct Ngap_ProtocolIE_Container_9666P44 {
  A_SEQUENCE_OF(struct Ngap_DownlinkRANStatusTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P44_t;
typedef struct Ngap_ProtocolIE_Container_9666P45 {
  A_SEQUENCE_OF(struct Ngap_PagingIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P45_t;
typedef struct Ngap_ProtocolIE_Container_9666P46 {
  A_SEQUENCE_OF(struct Ngap_InitialUEMessage_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P46_t;
typedef struct Ngap_ProtocolIE_Container_9666P47 {
  A_SEQUENCE_OF(struct Ngap_DownlinkNASTransport_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P47_t;
typedef struct Ngap_ProtocolIE_Container_9666P48 {
  A_SEQUENCE_OF(struct Ngap_UplinkNASTransport_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P48_t;
typedef struct Ngap_ProtocolIE_Container_9666P49 {
  A_SEQUENCE_OF(struct Ngap_NASNonDeliveryIndication_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P49_t;
typedef struct Ngap_ProtocolIE_Container_9666P50 {
  A_SEQUENCE_OF(struct Ngap_RerouteNASRequest_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P50_t;
typedef struct Ngap_ProtocolIE_Container_9666P51 {
  A_SEQUENCE_OF(struct Ngap_NGSetupRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P51_t;
typedef struct Ngap_ProtocolIE_Container_9666P52 {
  A_SEQUENCE_OF(struct Ngap_NGSetupResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P52_t;
typedef struct Ngap_ProtocolIE_Container_9666P53 {
  A_SEQUENCE_OF(struct Ngap_NGSetupFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P53_t;
typedef struct Ngap_ProtocolIE_Container_9666P54 {
  A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P54_t;
typedef struct Ngap_ProtocolIE_Container_9666P55 {
  A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P55_t;
typedef struct Ngap_ProtocolIE_Container_9666P56 {
  A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P56_t;
typedef struct Ngap_ProtocolIE_Container_9666P57 {
  A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P57_t;
typedef struct Ngap_ProtocolIE_Container_9666P58 {
  A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P58_t;
typedef struct Ngap_ProtocolIE_Container_9666P59 {
  A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P59_t;
typedef struct Ngap_ProtocolIE_Container_9666P60 {
  A_SEQUENCE_OF(struct Ngap_AMFStatusIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P60_t;
typedef struct Ngap_ProtocolIE_Container_9666P61 {
  A_SEQUENCE_OF(struct Ngap_NGResetIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P61_t;
typedef struct Ngap_ProtocolIE_Container_9666P62 {
  A_SEQUENCE_OF(struct Ngap_NGResetAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P62_t;
typedef struct Ngap_ProtocolIE_Container_9666P63 {
  A_SEQUENCE_OF(struct Ngap_ErrorIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P63_t;
typedef struct Ngap_ProtocolIE_Container_9666P64 {
  A_SEQUENCE_OF(struct Ngap_OverloadStartIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P64_t;
typedef struct Ngap_ProtocolIE_Container_9666P65 {
  A_SEQUENCE_OF(struct Ngap_OverloadStopIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P65_t;
typedef struct Ngap_ProtocolIE_Container_9666P66 {
  A_SEQUENCE_OF(struct Ngap_UplinkRANConfigurationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P66_t;
typedef struct Ngap_ProtocolIE_Container_9666P67 {
  A_SEQUENCE_OF(struct Ngap_DownlinkRANConfigurationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P67_t;
typedef struct Ngap_ProtocolIE_Container_9666P68 {
  A_SEQUENCE_OF(struct Ngap_WriteReplaceWarningRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P68_t;
typedef struct Ngap_ProtocolIE_Container_9666P69 {
  A_SEQUENCE_OF(struct Ngap_WriteReplaceWarningResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P69_t;
typedef struct Ngap_ProtocolIE_Container_9666P70 {
  A_SEQUENCE_OF(struct Ngap_PWSCancelRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P70_t;
typedef struct Ngap_ProtocolIE_Container_9666P71 {
  A_SEQUENCE_OF(struct Ngap_PWSCancelResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P71_t;
typedef struct Ngap_ProtocolIE_Container_9666P72 {
  A_SEQUENCE_OF(struct Ngap_PWSRestartIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P72_t;
typedef struct Ngap_ProtocolIE_Container_9666P73 {
  A_SEQUENCE_OF(struct Ngap_PWSFailureIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P73_t;
typedef struct Ngap_ProtocolIE_Container_9666P74 {
  A_SEQUENCE_OF(struct Ngap_DownlinkUEAssociatedNRPPaTransportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P74_t;
typedef struct Ngap_ProtocolIE_Container_9666P75 {
  A_SEQUENCE_OF(struct Ngap_UplinkUEAssociatedNRPPaTransportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P75_t;
typedef struct Ngap_ProtocolIE_Container_9666P76 {
  A_SEQUENCE_OF(struct Ngap_DownlinkNonUEAssociatedNRPPaTransportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P76_t;
typedef struct Ngap_ProtocolIE_Container_9666P77 {
  A_SEQUENCE_OF(struct Ngap_UplinkNonUEAssociatedNRPPaTransportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P77_t;
typedef struct Ngap_ProtocolIE_Container_9666P78 {
  A_SEQUENCE_OF(struct Ngap_TraceStartIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P78_t;
typedef struct Ngap_ProtocolIE_Container_9666P79 {
  A_SEQUENCE_OF(struct Ngap_TraceFailureIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P79_t;
typedef struct Ngap_ProtocolIE_Container_9666P80 {
  A_SEQUENCE_OF(struct Ngap_DeactivateTraceIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P80_t;
typedef struct Ngap_ProtocolIE_Container_9666P81 {
  A_SEQUENCE_OF(struct Ngap_CellTrafficTraceIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P81_t;
typedef struct Ngap_ProtocolIE_Container_9666P82 {
  A_SEQUENCE_OF(struct Ngap_LocationReportingControlIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P82_t;
typedef struct Ngap_ProtocolIE_Container_9666P83 {
  A_SEQUENCE_OF(struct Ngap_LocationReportingFailureIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P83_t;
typedef struct Ngap_ProtocolIE_Container_9666P84 {
  A_SEQUENCE_OF(struct Ngap_LocationReportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P84_t;
typedef struct Ngap_ProtocolIE_Container_9666P85 {
  A_SEQUENCE_OF(struct Ngap_UETNLABindingReleaseRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P85_t;
typedef struct Ngap_ProtocolIE_Container_9666P86 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityInfoIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P86_t;
typedef struct Ngap_ProtocolIE_Container_9666P87 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityCheckRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P87_t;
typedef struct Ngap_ProtocolIE_Container_9666P88 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityCheckResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P88_t;
typedef struct Ngap_ProtocolIE_Container_9666P89 {
  A_SEQUENCE_OF(struct Ngap_SecondaryRATDataUsageReportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P89_t;
typedef struct Ngap_ProtocolIE_Container_9666P90 {
  A_SEQUENCE_OF(struct Ngap_UplinkRIMInformationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P90_t;
typedef struct Ngap_ProtocolIE_Container_9666P91 {
  A_SEQUENCE_OF(struct Ngap_DownlinkRIMInformationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P91_t;
typedef struct Ngap_ProtocolIE_Container_9666P92 {
  A_SEQUENCE_OF(struct Ngap_ConnectionEstablishmentIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P92_t;
typedef struct Ngap_ProtocolIE_Container_9666P93 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityIDMappingRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P93_t;
typedef struct Ngap_ProtocolIE_Container_9666P94 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityIDMappingResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P94_t;
typedef struct Ngap_ProtocolIE_Container_9666P95 {
  A_SEQUENCE_OF(struct Ngap_AMFCPRelocationIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P95_t;
typedef struct Ngap_ProtocolIE_Container_9666P96 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyRequestTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P96_t;
typedef struct Ngap_ProtocolIE_Container_9666P97 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupRequestTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_9666P97_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P0;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P0_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P0_1[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P1;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P1_specs_3;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P1_3[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P2;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P2_specs_5;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P2_5[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P3;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P3_specs_7;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P3_7[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P4;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P4_specs_9;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P4_9[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P5;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P5_specs_11;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P5_11[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P6;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P6_specs_13;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P6_13[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P7;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P7_specs_15;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P7_15[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P8;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P8_specs_17;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P8_17[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P9;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_9666P9_specs_19;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P9_19[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P10;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P10_specs_21;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P10_21[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P11;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P11_specs_23;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P11_23[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P12;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P12_specs_25;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P12_25[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P13;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P13_specs_27;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P13_27[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P14;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P14_specs_29;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P14_29[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P15;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P15_specs_31;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P15_31[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P16;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P16_specs_33;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P16_33[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P17;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P17_specs_35;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P17_35[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P18;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P18_specs_37;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P18_37[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P19;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P19_specs_39;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P19_39[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P20;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P20_specs_41;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P20_41[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P21;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P21_specs_43;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P21_43[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P22;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P22_specs_45;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P22_45[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P23;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P23_specs_47;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P23_47[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P24;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P24_specs_49;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P24_49[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P25;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P25_specs_51;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P25_51[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P26;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P26_specs_53;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P26_53[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P27;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P27_specs_55;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P27_55[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P28;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P28_specs_57;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P28_57[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P29;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P29_specs_59;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P29_59[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P30;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P30_specs_61;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P30_61[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P31;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P31_specs_63;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P31_63[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P32;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P32_specs_65;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P32_65[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P33;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P33_specs_67;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P33_67[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P34;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P34_specs_69;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P34_69[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P35;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P35_specs_71;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P35_71[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P36;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P36_specs_73;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P36_73[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P37;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P37_specs_75;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P37_75[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P38;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P38_specs_77;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P38_77[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P39;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P39_specs_79;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P39_79[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P40;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P40_specs_81;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P40_81[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P41;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P41_specs_83;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P41_83[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P42;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P42_specs_85;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P42_85[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P43;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P43_specs_87;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P43_87[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P44;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P44_specs_89;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P44_89[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P45;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P45_specs_91;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P45_91[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P46;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P46_specs_93;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P46_93[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P47;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P47_specs_95;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P47_95[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P48;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P48_specs_97;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P48_97[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P49;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P49_specs_99;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P49_99[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P50;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P50_specs_101;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P50_101[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P51;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P51_specs_103;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P51_103[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P52;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P52_specs_105;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P52_105[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P53;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P53_specs_107;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P53_107[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P54;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P54_specs_109;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P54_109[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P55;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P55_specs_111;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P55_111[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P56;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P56_specs_113;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P56_113[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P57;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P57_specs_115;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P57_115[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P58;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P58_specs_117;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P58_117[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P59;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P59_specs_119;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P59_119[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P60;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P60_specs_121;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P60_121[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P61;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P61_specs_123;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P61_123[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P62;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P62_specs_125;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P62_125[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P63;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P63_specs_127;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P63_127[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P64;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P64_specs_129;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P64_129[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P65;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P65_specs_131;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P65_131[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P66;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P66_specs_133;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P66_133[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P67;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P67_specs_135;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P67_135[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P68;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P68_specs_137;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P68_137[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P69;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P69_specs_139;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P69_139[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P70;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P70_specs_141;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P70_141[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P71;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P71_specs_143;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P71_143[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P72;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P72_specs_145;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P72_145[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P73;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P73_specs_147;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P73_147[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P74;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P74_specs_149;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P74_149[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P75;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P75_specs_151;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P75_151[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P76;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P76_specs_153;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P76_153[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P77;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P77_specs_155;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P77_155[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P78;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P78_specs_157;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P78_157[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P79;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P79_specs_159;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P79_159[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P80;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P80_specs_161;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P80_161[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P81;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P81_specs_163;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P81_163[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P82;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P82_specs_165;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P82_165[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P83;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P83_specs_167;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P83_167[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P84;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P84_specs_169;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P84_169[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P85;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P85_specs_171;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P85_171[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P86;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P86_specs_173;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P86_173[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P87;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P87_specs_175;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P87_175[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P88;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P88_specs_177;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P88_177[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P89;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P89_specs_179;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P89_179[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P90;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P90_specs_181;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P90_181[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P91;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P91_specs_183;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P91_183[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P92;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P92_specs_185;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P92_185[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P93;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P93_specs_187;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P93_187[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P94;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P94_specs_189;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P94_189[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P95;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P95_specs_191;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P95_191[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P96;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P96_specs_193;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P96_193[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_9666P97;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_9666P97_specs_195;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_9666P97_195[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_9666P97_constr_195;

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_ProtocolIE_Container_H_ */
#include <asn_internal.h>
