/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice
 * -gen-PER -D src`
 */

#include "Ngap_SourceNodeID.h"

#include "Ngap_GlobalGNB-ID.h"
static asn_oer_constraints_t asn_OER_type_Ngap_SourceNodeID_constr_1
    CC_NOTUSED = {{0, 0}, -1};
asn_per_constraints_t asn_PER_type_Ngap_SourceNodeID_constr_1 CC_NOTUSED = {
    {APC_CONSTRAINED | APC_EXTENSIBLE, 0, 0, 0, 0} /* (0..0,...) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
asn_TYPE_member_t asn_MBR_Ngap_SourceNodeID_1[] = {
    {ATF_POINTER,
     0,
     offsetof(struct Ngap_SourceNodeID, choice.sourceengNB_ID),
     (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_Ngap_GlobalGNB_ID,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "sourceengNB-ID"},
};
static const asn_TYPE_tag2member_t asn_MAP_Ngap_SourceNodeID_tag2el_1[] = {
    {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0} /* sourceengNB-ID */
};
asn_CHOICE_specifics_t asn_SPC_Ngap_SourceNodeID_specs_1 = {
    sizeof(struct Ngap_SourceNodeID),
    offsetof(struct Ngap_SourceNodeID, _asn_ctx),
    offsetof(struct Ngap_SourceNodeID, present),
    sizeof(((struct Ngap_SourceNodeID*) 0)->present),
    asn_MAP_Ngap_SourceNodeID_tag2el_1,
    1, /* Count of tags in the map */
    0,
    0,
    1 /* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Ngap_SourceNodeID = {
    "SourceNodeID",
    "SourceNodeID",
    &asn_OP_CHOICE,
    0, /* No effective tags (pointer) */
    0, /* No effective tags (count) */
    0, /* No tags (pointer) */
    0, /* No tags (count) */
    {&asn_OER_type_Ngap_SourceNodeID_constr_1,
     &asn_PER_type_Ngap_SourceNodeID_constr_1, CHOICE_constraint},
    asn_MBR_Ngap_SourceNodeID_1,
    1,                                 /* Elements count */
    &asn_SPC_Ngap_SourceNodeID_specs_1 /* Additional specs */
};
