/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N1N2MessageCollectionDocumentApiImpl.h"

#include "amf_app.hpp"
#include "amf_conversions.hpp"
#include "amf_sbi.hpp"
#include "itti.hpp"
#include "output_wrapper.hpp"
#include "pdu_session_context.hpp"

using namespace amf_application;

extern itti_mw* itti_inst;
extern amf_app* amf_app_inst;

namespace oai {
namespace amf {
namespace api {

using namespace oai::_3gpp::model;

namespace {
nlohmann::json make_success_body(const paging::admission_result& result) {
  N1N2MessageTransferRspData rsp = {};
  N1N2MessageTransferCause cause = {};
  cause.setEnumValue(result.cause);
  rsp.setCause(cause);
  auto body = nlohmann::json(rsp);
  if (result.cause ==
          N1N2MessageTransferCause_anyOf::eN1N2MessageTransferCause_anyOf::
              WAITING_FOR_ASYNCHRONOUS_TRANSFER &&
      result.max_waiting_time.has_value()) {
    body["maxWaitingTime"] = result.max_waiting_time.value();
  }
  return body;
}

nlohmann::json make_error_body(const paging::admission_result& result) {
  ProblemDetails problem = {};
  problem.setStatus(result.http_status_code);
  if (!result.problem_cause.empty()) {
    problem.setCause(result.problem_cause);
  }
  if (!result.problem_detail.empty()) {
    problem.setDetail(result.problem_detail);
  }

  N1N2MessageTransferError error = {};
  error.setError(problem);
  if (result.max_waiting_time.has_value()) {
    N1N2MsgTxfrErrDetail detail = {};
    detail.setMaxWaitingTime(result.max_waiting_time.value());
    error.setErrInfo(detail);
  }
  return nlohmann::json(error);
}
}  // namespace

N1N2MessageCollectionDocumentApiImpl::N1N2MessageCollectionDocumentApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr,
    amf_application::amf_app* amf_app_inst)
    : N1N2MessageCollectionDocumentApi(rtr), m_amf_app(amf_app_inst) {}

void N1N2MessageCollectionDocumentApiImpl::n1_n2_message_transfer(
    const std::string& ueContextId,
    std::unordered_map<std::string, oai::utils::mime_part>& parts,
    Pistache::Http::ResponseWriter& response) {
  Logger::amf_server().debug(
      "Receive N1N2MessageTransfer Request, handling...");

  nlohmann::json response_json = {};
  response_json["cause"] =
      n1_n2_message_transfer_cause_e2str[N1_MSG_NOT_TRANSFERRED];
  Pistache::Http::Code code = Pistache::Http::Code::Bad_Request;

  std::string supi = ueContextId;

  N1N2MessageTransferReqData n1N2MessageTransferReqData = {};
  nlohmann::json::parse(parts[oai::utils::JSON_CONTENT_ID_MIME].body.c_str())
      .get_to(n1N2MessageTransferReqData);

  bool request_valid = true;
  bstring n1sm       = nullptr;
  bstring n2sm       = nullptr;
  bstring nrppa_pdu  = nullptr;
  bstring routing_id = nullptr;

  auto itti_msg = std::make_shared<itti_n1n2_message_transfer_request>(
      AMF_SERVER, TASK_AMF_APP);  // TODO: May not be used
  itti_msg->supi = ueContextId;
  Logger::amf_server().debug("SUPI %s", ueContextId.c_str());

  if (n1N2MessageTransferReqData.n2InfoContainerIsSet()) {
    // N2 Container Present
    Logger::amf_server().debug("N2InfoContainer is present, handling...");

    std::string n2_content_id = {};
    std::string ngap_type     = {};

    // Check N2 Information Class
    switch (n1N2MessageTransferReqData.getN2InfoContainer()
                .getN2InformationClass()
                .getEnumValue()) {
      case N2InformationClass_anyOf::eN2InformationClass_anyOf::SM: {
        Logger::amf_server().debug("N2 Information Class: SM");

        // Validate Content ID
        n2_content_id = n1N2MessageTransferReqData.getN2InfoContainer()
                            .getSmInfo()
                            .getN2InfoContent()
                            .getNgapData()
                            .getContentId();
        Logger::amf_server().debug("n2_content_id: %s", n2_content_id.c_str());
        // Check whether N2 Content Id is valid with MIME part
        if (parts.count(n2_content_id) == 0 ||
            parts[n2_content_id].body.size() == 0) {
          Logger::amf_server().error("Missing n2sm MIME part");
          send_response(code, response_json, response);
          return;
        }

        // NGAP IE Type
        nlohmann::json ngap_ie_type_json = {};
        to_json(
            ngap_ie_type_json, n1N2MessageTransferReqData.getN2InfoContainer()
                                   .getSmInfo()
                                   .getN2InfoContent()
                                   .getNgapIeType()
                                   .getValue());
        ngap_type = ngap_ie_type_json.get<std::string>();
        Logger::amf_server().debug("NGAP IE Type: %s", ngap_type.c_str());
        // Set NGAP type
        itti_msg->n2sm_info_type = ngap_type;

        Logger::amf_server().debug(
            "Key for PDU Session Context: SUPI (%s)", supi.c_str());
        std::shared_ptr<pdu_session_context> psc = {};

        if (!amf_app_inst->get_pdu_session_context(
                supi, (uint8_t) n1N2MessageTransferReqData.getPduSessionId(),
                psc)) {
          send_response(code, response_json, response);
          return;
        }

        amf_conv::msg_str_2_msg_hex(parts[n2_content_id].body, n2sm);
        // Store N2 SM in PDU Session Context
        psc->n2sm              = bstrcpy(n2sm);
        psc->is_n2sm_available = true;

        itti_msg->n2sm           = bstrcpy(n2sm);
        itti_msg->is_n2sm_set    = true;
        itti_msg->n2sm_info_type = ngap_type;

        itti_msg->pdu_session_id =
            (uint8_t) n1N2MessageTransferReqData.getPduSessionId();

      } break;

      case N2InformationClass_anyOf::eN2InformationClass_anyOf::NRPPA: {
        Logger::amf_server().debug("N2 Information Class: NRPPA");
        n2_content_id = n1N2MessageTransferReqData.getN2InfoContainer()
                            .getNrppaInfo()
                            .getNrppaPdu()
                            .getNgapData()
                            .getContentId();
        Logger::amf_server().debug("N2 Content Id: %s", n2_content_id.c_str());

        // Check whether N2 Content Id is valid with MIME part
        if (parts.count(n2_content_id) == 0 ||
            parts[n2_content_id].body.size() == 0) {
          Logger::amf_server().error("Missing n2sm MIME part");
          send_response(code, response_json, response);
          return;
        }

        // NGAP IE Type
        nlohmann::json ngap_ie_type_json = {};
        to_json(
            ngap_ie_type_json, n1N2MessageTransferReqData.getN2InfoContainer()
                                   .getNrppaInfo()
                                   .getNrppaPdu()
                                   .getNgapIeType()
                                   .getValue());
        ngap_type = ngap_ie_type_json.get<std::string>();
        Logger::amf_server().debug("NGAP IE Type: %s", ngap_type.c_str());
        // Set NGAP type
        itti_msg->n2sm_info_type = ngap_type;

        // NRPPA PDU
        amf_conv::msg_str_2_msg_hex(parts[n2_content_id].body, nrppa_pdu);
        amf_conv::string_2_bstring(
            n1N2MessageTransferReqData.getN2InfoContainer()
                .getNrppaInfo()
                .getNfId(),
            routing_id);
        itti_msg->nrppa_pdu        = bstrcpy(nrppa_pdu);
        itti_msg->routing_id       = bstrcpy(routing_id);
        itti_msg->is_nrppa_pdu_set = true;

      } break;

      default: {
        /*
        response_json["cause"] =
            n1_n2_message_transfer_cause_e2str[N1_MSG_NOT_TRANSFERRED];
        code = Pistache::Http::Code::Bad_Request;
        send_response(code, response_json, response);
        */
        response.send(
            Pistache::Http::Code::Ok,
            "N1N2MessageCollectionDocumentApiImpl::n1_n2_message_transfer API "
            "(Unsupported N2 Message Class)");
        return;
      }
    }
  }

  if (n1N2MessageTransferReqData.n1MessageContainerIsSet()) {
    Logger::amf_server().debug("N1MessageContainer is present, handling...");

    switch (n1N2MessageTransferReqData.getN1MessageContainer()
                .getN1MessageClass()
                .getEnumValue()) {
      case N1MessageClass_anyOf::eN1MessageClass_anyOf::SM: {
        // N1 SM Container Present
        Logger::amf_server().debug(
            "Key for PDU Session Context: SUPI (%s)", supi.c_str());
        std::shared_ptr<pdu_session_context> psc = {};
        if (!amf_app_inst->get_pdu_session_context(
                supi, (uint8_t) n1N2MessageTransferReqData.getPduSessionId(),
                psc)) {
          send_response(code, response_json, response);
          return;
        }

        std::string n1_content_id =
            n1N2MessageTransferReqData.getN1MessageContainer()
                .getN1MessageContent()
                .getContentId();
        Logger::amf_server().debug("N1 Content Id: %s", n1_content_id.c_str());

        if (parts.count(n1_content_id) == 0 ||
            parts[n1_content_id].body.size() == 0) {
          send_response(code, response_json, response);
          return;
        }

        amf_conv::msg_str_2_msg_hex(
            parts[n1_content_id].body.substr(
                0, parts[n1_content_id].body.length()),
            n1sm);
        oai::utils::output_wrapper::print_buffer(
            "amf_server", "Received N1 SM", (uint8_t*) bdata(n1sm),
            blength(n1sm));
        // Store N1 SM in PDU Session Context
        psc->n1sm              = bstrcpy(n1sm);
        psc->is_n1sm_available = true;

        itti_msg->n1sm        = bstrcpy(n1sm);
        itti_msg->is_n1sm_set = true;
        itti_msg->pdu_session_id =
            (uint8_t) n1N2MessageTransferReqData.getPduSessionId();

      } break;

      case N1MessageClass_anyOf::eN1MessageClass_anyOf::LPP: {
        // N1 LPP Container Present
        // TODO:
        response.send(
            Pistache::Http::Code::Ok,
            "N1N2MessageCollectionDocumentApiImpl::n1_n2_message_transfer API "
            "(Unsupported N1 Message Class: LPP)");
        return;
      } break;

      default: {
        // TODO:
        response.send(
            Pistache::Http::Code::Ok,
            "N1N2MessageCollectionDocumentApiImpl::n1_n2_message_transfer API "
            "(Unsupported N1 Message Class)");
        return;
      }
    }
  }

  if (!request_valid) {
    code = Pistache::Http::Code::Bad_Request;
    response_json["cause"] =
        n1_n2_message_transfer_cause_e2str[N1_MSG_NOT_TRANSFERRED];
    // Send response to the NF Service Consumer (e.g., SMF)
    response.send(code, response_json.dump().c_str());
    return;
  }

  if (n1N2MessageTransferReqData.ppiIsSet()) {
    itti_msg->is_ppi_set = true;
    itti_msg->ppi        = n1N2MessageTransferReqData.getPpi();
  } else {
    itti_msg->is_ppi_set = false;
  }

  itti_msg->is_skip_ind_set = n1N2MessageTransferReqData.skipIndIsSet();
  if (itti_msg->is_skip_ind_set) {
    itti_msg->skip_ind = n1N2MessageTransferReqData.isSkipInd();
  }

  itti_msg->is_last_msg_indication_set =
      n1N2MessageTransferReqData.lastMsgIndicationIsSet();
  if (itti_msg->is_last_msg_indication_set) {
    itti_msg->last_msg_indication =
        n1N2MessageTransferReqData.isLastMsgIndication();
  }

  itti_msg->is_lcs_correlation_id_set =
      n1N2MessageTransferReqData.lcsCorrelationIdIsSet();
  if (itti_msg->is_lcs_correlation_id_set) {
    itti_msg->lcs_correlation_id =
        n1N2MessageTransferReqData.getLcsCorrelationId();
  }

  itti_msg->is_arp_set = n1N2MessageTransferReqData.arpIsSet();
  if (itti_msg->is_arp_set) {
    itti_msg->arp = n1N2MessageTransferReqData.getArp();
  }

  itti_msg->is_r5qi_set = n1N2MessageTransferReqData.r5qiIsSet();
  if (itti_msg->is_r5qi_set) {
    itti_msg->r5qi = static_cast<uint8_t>(n1N2MessageTransferReqData.getR5qi());
  }

  if (n1N2MessageTransferReqData.n1n2FailureTxfNotifURIIsSet()) {
    itti_msg->n1n2_failure_txf_notif_uri =
        n1N2MessageTransferReqData.getN1n2FailureTxfNotifURI();
  }

  itti_msg->is_smf_reallocation_ind_set =
      n1N2MessageTransferReqData.smfReallocationIndIsSet();
  if (itti_msg->is_smf_reallocation_ind_set) {
    itti_msg->smf_reallocation_ind =
        n1N2MessageTransferReqData.isSmfReallocationInd();
  }

  itti_msg->is_area_of_validity_set =
      n1N2MessageTransferReqData.areaOfValidityIsSet();
  if (itti_msg->is_area_of_validity_set) {
    itti_msg->area_of_validity = n1N2MessageTransferReqData.getAreaOfValidity();
  }

  itti_msg->is_supported_features_set =
      n1N2MessageTransferReqData.supportedFeaturesIsSet();
  if (itti_msg->is_supported_features_set) {
    itti_msg->supported_features =
        n1N2MessageTransferReqData.getSupportedFeatures();
  }

  itti_msg->is_old_guami_set = n1N2MessageTransferReqData.oldGuamiIsSet();
  if (itti_msg->is_old_guami_set) {
    itti_msg->old_guami = n1N2MessageTransferReqData.getOldGuami();
  }

  itti_msg->is_ma_accepted_ind_set =
      n1N2MessageTransferReqData.maAcceptedIndIsSet();
  if (itti_msg->is_ma_accepted_ind_set) {
    itti_msg->ma_accepted_ind = n1N2MessageTransferReqData.isMaAcceptedInd();
  }

  itti_msg->is_ext_buf_support_set =
      n1N2MessageTransferReqData.extBufSupportIsSet();
  if (itti_msg->is_ext_buf_support_set) {
    itti_msg->ext_buf_support = n1N2MessageTransferReqData.isExtBufSupport();
  }

  itti_msg->is_target_access_set =
      n1N2MessageTransferReqData.targetAccessIsSet();
  if (itti_msg->is_target_access_set) {
    itti_msg->target_access = n1N2MessageTransferReqData.getTargetAccess();
  }

  itti_msg->is_nf_id_set = n1N2MessageTransferReqData.nfIdIsSet();
  if (itti_msg->is_nf_id_set) {
    itti_msg->nf_id = n1N2MessageTransferReqData.getNfId();
  }

  auto result = m_amf_app->handle_n1n2_message_transfer_request(*itti_msg);
  code        = static_cast<Pistache::Http::Code>(result.http_status_code);
  if (result.is_error) {
    response.send(code, make_error_body(result).dump().c_str());
  } else {
    response.send(code, make_success_body(result).dump().c_str());
  }

  oai::utils::utils::bdestroy_wrapper(&n1sm);
  oai::utils::utils::bdestroy_wrapper(&n2sm);
  oai::utils::utils::bdestroy_wrapper(&nrppa_pdu);
  oai::utils::utils::bdestroy_wrapper(&routing_id);
}

void N1N2MessageCollectionDocumentApiImpl::send_response(
    const Pistache::Http::Code& code, const nlohmann::json& response_json,
    Pistache::Http::ResponseWriter& response) {
  response.send(code, response_json.dump().c_str());
}

}  // namespace api
}  // namespace amf
}  // namespace oai
