/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N1N2SubscriptionsCollectionForIndividualUEContextsDocumentApiImpl.h"

#include "3gpp_29.500.h"
#include "itti.hpp"
#include "amf_sbi_promise.hpp"
#include "utils.hpp"

namespace oai {
namespace amf {
namespace api {

using namespace oai::_3gpp::model;

N1N2SubscriptionsCollectionForIndividualUEContextsDocumentApiImpl::
    N1N2SubscriptionsCollectionForIndividualUEContextsDocumentApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr,
        amf_application::amf_app* amf_app_inst)
    : N1N2SubscriptionsCollectionForIndividualUEContextsDocumentApi(rtr),
      m_amf_app(amf_app_inst) {}

void N1N2SubscriptionsCollectionForIndividualUEContextsDocumentApiImpl::
    n1_n2_message_subscribe(
        const std::string& ueContextId,
        const UeN1N2InfoSubscriptionCreateData&
            ueN1N2InfoSubscriptionCreateData,
        Pistache::Http::ResponseWriter& response) {
  Logger::amf_server().debug("Receive N1N2MessageSubscribe, handling...");
  Logger::amf_server().debug("UE Context ID (%s)", ueContextId.c_str());

  oai::amf::sbi::sbi_result_t result_data = oai::amf::sbi::sbi_send_recv(
      m_amf_app, [&](uint32_t promise_id) -> std::shared_ptr<itti_msg> {
        // Handle the N1N2SubscribeMessage in amf_app
        std::shared_ptr<itti_sbi_n1n2_message_subscribe> itti_msg =
            std::make_shared<itti_sbi_n1n2_message_subscribe>(
                TASK_AMF_SBI, TASK_AMF_APP, promise_id);
        itti_msg->ue_cxt_id         = ueContextId;
        itti_msg->subscription_data = ueN1N2InfoSubscriptionCreateData;
        itti_msg->promise_id        = promise_id;
        return itti_msg;
      });

  if (result_data.has_result) {
    nlohmann::json& result = result_data.body;
    // process data
    std::string location        = result_data.location;
    uint32_t http_response_code = result_data.http_code;

    // UeN1N2InfoSubscriptionCreatedData
    nlohmann::json json_data = {};
    if (result.find(kSbiResponseJsonData) != result.end()) {
      json_data = result[kSbiResponseJsonData];
    }

    if (http_response_code == oai::common::sbi::http_status_code::CREATED) {
      response.headers().add<Pistache::Http::Header::Location>(
          location);  // Location header
      response.headers().add<Pistache::Http::Header::ContentType>(
          Pistache::Http::Mime::MediaType("application/json"));
      response.send(Pistache::Http::Code::Created, json_data.dump().c_str());
    } else {
      response.send(Pistache::Http::Code(http_response_code));
    }
  } else {
    // TODO:
    response.send(Pistache::Http::Code::Gateway_Timeout);
  }
}

}  // namespace api
}  // namespace amf
}  // namespace oai
