/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N1N2IndividualSubscriptionDocumentApiImpl.h"

#include "3gpp_29.500.h"
#include "amf_sbi_promise.hpp"
#include "utils.hpp"

namespace oai {
namespace amf {
namespace api {

N1N2IndividualSubscriptionDocumentApiImpl::
    N1N2IndividualSubscriptionDocumentApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr,
        amf_application::amf_app* amf_app_inst)
    : N1N2IndividualSubscriptionDocumentApi(rtr), m_amf_app(amf_app_inst) {}

void N1N2IndividualSubscriptionDocumentApiImpl::n1_n2_message_un_subscribe(
    const std::string& ueContextId, const std::string& subscriptionId,
    Pistache::Http::ResponseWriter& response) {
  Logger::amf_server().debug("Receive N1N2MessageUnsubscribe, handling...");
  Logger::amf_server().debug(
      "UE Context ID %s, Subscription ID %s", ueContextId.c_str(),
      subscriptionId.c_str());

  oai::amf::sbi::sbi_result_t result_data = oai::amf::sbi::sbi_send_recv(
      m_amf_app, [&](uint32_t promise_id) -> std::shared_ptr<itti_msg> {
        // Handle the N1N2UnsubscribeMessage in amf_app
        std::shared_ptr<itti_sbi_n1n2_message_unsubscribe> itti_msg =
            std::make_shared<itti_sbi_n1n2_message_unsubscribe>(
                TASK_AMF_SBI, TASK_AMF_APP, promise_id);
        itti_msg->ue_cxt_id       = ueContextId;
        itti_msg->subscription_id = subscriptionId;
        itti_msg->promise_id      = promise_id;
        return itti_msg;
      });

  if (result_data.has_result) {
    nlohmann::json& result = result_data.body;
    // process data
    uint32_t http_response_code = result_data.http_code;

    if (http_response_code == oai::common::sbi::http_status_code::NO_CONTENT) {
      response.send(Pistache::Http::Code::No_Content);
    } else {
      // Problem//details
      nlohmann::json json_data = {};
      if (result.find("ProblemDetails") != result.end()) {
        json_data = result["ProblemDetails"];
      }

      response.headers().add<Pistache::Http::Header::ContentType>(
          Pistache::Http::Mime::MediaType("application/problem+json"));
      response.send(
          Pistache::Http::Code(http_response_code), json_data.dump().c_str());
    }
  } else {
    // TODO:
    response.send(Pistache::Http::Code::Gateway_Timeout);
  }
}

}  // namespace api
}  // namespace amf
}  // namespace oai
