/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NonUEN2MessageNotificationIndividualSubscriptionDocumentApiImpl.h"

#include "amf_sbi_promise.hpp"

namespace oai {
namespace amf {
namespace api {

NonUEN2MessageNotificationIndividualSubscriptionDocumentApiImpl::
    NonUEN2MessageNotificationIndividualSubscriptionDocumentApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr,
        amf_application::amf_app* amf_app_inst)
    : NonUEN2MessageNotificationIndividualSubscriptionDocumentApi(rtr),
      m_amf_app(amf_app_inst) {}

void NonUEN2MessageNotificationIndividualSubscriptionDocumentApiImpl::
    non_ue_n2_info_un_subscribe(
        const std::string& n2NotifySubscriptionId,
        Pistache::Http::ResponseWriter& response) {
  Logger::amf_server().debug("Receive NonUeN2InfoUnSubscribe, handling...");
  Logger::amf_server().debug(
      "Subscription ID %s", n2NotifySubscriptionId.c_str());

  oai::amf::sbi::sbi_result_t result_data = oai::amf::sbi::sbi_send_recv(
      m_amf_app, [&](uint32_t promise_id) -> std::shared_ptr<itti_msg> {
        // Handle the NonUEN2InfoUnsubscribe in amf_app
        std::shared_ptr<itti_sbi_non_ue_n2_info_unsubscribe> itti_msg =
            std::make_shared<itti_sbi_non_ue_n2_info_unsubscribe>(
                TASK_AMF_SBI, TASK_AMF_APP, promise_id);
        itti_msg->subscription_id = n2NotifySubscriptionId;
        itti_msg->promise_id      = promise_id;
        return itti_msg;
      });

  if (result_data.has_result) {
    nlohmann::json& result = result_data.body;
    // process data
    uint32_t http_response_code = result_data.http_code;
    nlohmann::json json_data    = {};

    if (http_response_code == oai::common::sbi::http_status_code::NO_CONTENT) {
      response.send(Pistache::Http::Code(http_response_code));
    } else {
      // Problem details
      if (result.find("ProblemDetails") != result.end()) {
        json_data = result["ProblemDetails"];
      }

      response.headers().add<Pistache::Http::Header::ContentType>(
          Pistache::Http::Mime::MediaType("application/problem+json"));
      response.send(
          Pistache::Http::Code(http_response_code), json_data.dump().c_str());
    }
  } else {
    response.send(Pistache::Http::Code::Gateway_Timeout);
  }
}

}  // namespace api
}  // namespace amf
}  // namespace oai
