/**
 * Nsmf_EventExposure
 * Session Management Event Exposure Service. © 2019, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * StatusNotifyApiImpl.h
 *
 *
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#ifndef STATUS_NOTIFY_API_IMPL_H_
#define STATUS_NOTIFY_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <pistache/optional.h>

#include "StatusNotifyApi.h"
#include "ProblemDetails.h"
#include "amf_app.hpp"

namespace oai {
namespace amf {
namespace api {

using namespace oai::_3gpp::model;

class StatusNotifyApiImpl : public oai::amf::api::StatusNotifyApi {
 public:
  StatusNotifyApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      amf_application::amf_app* amf_app_inst);
  ~StatusNotifyApiImpl() {}

  void receive_pdu_session_status_notification(
      const std::string& ueContextId, const std::string& pduSessionId,
      const SmContextStatusNotification& statusNotification,
      Pistache::Http::ResponseWriter& response);

 private:
  amf_application::amf_app* m_amf_app;
  // std::string m_address;
};

}  // namespace api
}  // namespace amf
}  // namespace oai

#endif
