/**
 * Nsmf_EventExposure
 * Session Management Event Exposure Service. © 2019, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include "3gpp_29.500.h"
#include "conversions.hpp"
#include "itti_msg_sbi.hpp"
#include "logger.hpp"
#include "amf_sbi_promise.hpp"
#include "StatusNotifyApiImpl.h"
#include "utils.hpp"

namespace oai {
namespace amf {
namespace api {

using namespace oai::_3gpp::model;

StatusNotifyApiImpl::StatusNotifyApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr,
    amf_application::amf_app* amf_app_inst)
    : StatusNotifyApi(rtr), m_amf_app(amf_app_inst) {}

void StatusNotifyApiImpl::receive_pdu_session_status_notification(
    const std::string& ueContextId, const std::string& pduSessionId,
    const SmContextStatusNotification& statusNotification,
    Pistache::Http::ResponseWriter& response) {
  Logger::amf_server().debug("Receive an NF Status Notify, handling...");

  uint8_t pdu_session_id = 0;
  if (oai::utils::conv::string_to_int8(pduSessionId, pdu_session_id)) {
    // TODO:
    Logger::amf_server().debug("Invalid PDU Session ID value");
    response.send(Pistache::Http::Code::No_Content);
  }

  oai::amf::sbi::sbi_result_t result_data = oai::amf::sbi::sbi_send_recv(
      m_amf_app, [&](uint32_t promise_id) -> std::shared_ptr<itti_msg> {
        // Handle the PDU Session Release in amf_app
        std::shared_ptr<itti_sbi_pdu_session_release_notif> itti_msg =
            std::make_shared<itti_sbi_pdu_session_release_notif>(
                TASK_AMF_SBI, TASK_AMF_APP, promise_id);
        itti_msg->promise_id                  = promise_id;
        itti_msg->ue_id                       = ueContextId;
        itti_msg->pdu_session_id              = pdu_session_id;
        itti_msg->smContextStatusNotification = statusNotification;
        return itti_msg;
      });

  if (result_data.has_result) {
    response.send(Pistache::Http::Code::No_Content);
  } else {
    // TODO:
    response.send(Pistache::Http::Code::Gateway_Timeout);
  }
}

}  // namespace api
}  // namespace amf
}  // namespace oai
